apiVersion: apps/v1
kind: Deployment
metadata:
  name: larisin-backend
  labels:
    app: larisin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: larisin-backend
  template:
    metadata:
      labels:
        app: larisin-backend
    spec:
      containers:
        - name: backend
          image: asia-southeast2-docker.pkg.dev/hology-67/larisin-repo/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DB_PATH
              value: "/data/larisin.db"
          volumeMounts:
            - name: backend-data
              mountPath: /data
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: larisin-backend-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: larisin-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: larisin-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: larisin-backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: larisin-frontend
  labels:
    app: larisin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: larisin-frontend
  template:
    metadata:
      labels:
        app: larisin-frontend
    spec:
      containers:
        - name: frontend
          image: asia-southeast2-docker.pkg.dev/hology-67/larisin-repo/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: INTERNAL_BACKEND_URL
              value: "http://larisin-backend-svc:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: larisin-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: larisin-frontend
  ports:
    - port: 80
      targetPort: 3000
